name: Mock Change Request Workflow

on:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
      subnet_info:
        required: false
        type: string
      state:
        required: true
        type: string
      close_code:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  mock-change-request:
    runs-on: ubuntu-latest
    env:
      SITE: ${{ inputs.site }}
      SUBNET_INFO: ${{ inputs.subnet_info }}
      STATE: ${{ inputs.state }}
      CLOSE_CODE: ${{ inputs.close_code }}

    steps:
      - name: Checkout calling repo (main repo)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.token }}

      - name: List files after checkout
        run: |
          echo "Listing files after checkout"
          ls -R

      - name: Setup Python and install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Generate mock inventories and files
        if: ${{ inputs.state == 'create' }}
        run: |
          echo "SITE: $SITE"
          echo "SUBNET_INFO: $SUBNET_INFO"
          export ANSIBLE_INVENTORY="/mock-data/common/inventory,/mock-data/$SITE/inventory"
          echo -e "host1\nhost2" > hostlist.txt
          echo "CI Name" > hosts.csv
          cat hostlist.txt >> hosts.csv
          sed 's/$/,/' hosts.csv > mock_host_list.csv

      - name: Download CR artifacts (for implement or close)
        if: ${{ inputs.state != 'create' }}
        uses: actions/download-artifact@v4
        with:
          name: cr-create-${{ inputs.site }}

      - name: Run change request script
        run: |
          if [[ "$STATE" == "create" ]]; then
            python3 ./mock_utils/mock_handle_cr.py --state create
          elif [[ "$STATE" == "implement" ]]; then
            python3 ./mock_utils/mock_handle_cr.py --state implement
          elif [[ "$STATE" == "close" ]]; then
            python3 ./mock_utils/mock_handle_cr.py --state close --close_code "$CLOSE_CODE"
          else
            echo "Invalid state"
            exit 1
          fi

      - name: List specific files
        run: |
          echo "Listing host list and change number files:"
          ls mock_host_list.csv mock_CHANGE_NUMBER.txt

      - name: Upload CR artifacts (only for create)
        if: ${{ inputs.state == 'create' }}
        uses: actions/upload-artifact@v4
        with:
          name: cr-create-${{ inputs.site }}
          path: |
            mock_host_list.csv
            mock_CHANGE_NUMBER.txt
          if-no-files-found: ignore
