name: Reusable Run Script

on:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      site:
        description: "enter"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reusable repo (Avee07/github-reusable-workflows)
        uses: actions/checkout@v4
        with:
          repository: Avee07/github-reusable-workflows
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List files (for debug)
        run: ls -R

      - name: Make script executable
        run: chmod +x utils/my-script.sh

      - name: Run script with input
        run: ./utils/my-script.sh "${{ inputs.site }}"
